import { defineConfig } from "oxfmt";

export default defineConfig({
	ignorePatterns: [".*", "assets", "docs", "public"],
	arrowParens: "avoid",
	bracketSameLine: false,
	bracketSpacing: true,
	singleQuote: false,
	trailingComma: "all",
	printWidth: 80,
	endOfLine: "lf",
	semi: true,
	useTabs: true,
	tabWidth: 2,
	proseWrap: "preserve",
	htmlWhitespaceSensitivity: "css",
	sortPackageJson: false,
	sortImports: {
		newlinesBetween: false,
		customGroups: [
			{ groupName: "react", elementNamePattern: ["react", "react/**"] },
			{
				groupName: "react-dom",
				elementNamePattern: ["react-dom", "react-dom/**"],
			},
			{ groupName: "react-native", elementNamePattern: ["react-native"] },
			{ groupName: "next", elementNamePattern: ["next", "next/**"] },
			{
				groupName: "fastify",
				elementNamePattern: ["fastify", "fastify/**", "fastify-**"],
			},
			{ groupName: "assets", elementNamePattern: ["@/assets/**"] },
		],
		groups: [
			"side_effect-builtin",
			"side_effect-external",
			"side_effect-type",
			"side_effect-import",
			{ newlinesBetween: true },
			"react",
			"react-dom",
			"react-native",
			"next",
			"fastify",
			"value-builtin",
			"value-external",
			"type-import",
			{ newlinesBetween: true },
			["type-internal", "value-internal"],
			["type-parent", "value-parent"],
			["type-sibling", "value-sibling"],
			["type-index", "value-index"],
			{ newlinesBetween: true },
			"side_effect-internal",
			"side_effect-parent",
			"side_effect-sibling",
			"side_effect-index",
			{ newlinesBetween: true },
			"assets",
			"style",
			{ newlinesBetween: true },
			"unknown",
		],
	},
	sortTailwindcss: {
		stylesheet: "./src/global.css",
		functions: ["clsx", "cn", "cva"],
		preserveWhitespace: false,
	},
});
